import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { CommentProvider } from "./globalContext/commentContext";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "interactive comment section",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <CommentProvider>
          {children}
        </CommentProvider>
      </body>
    </html>
  );
}
